version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date