version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: apt-get update    
      - run: apt-get install sshpass
      - run: apt-get install apt-transport-https
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - run: apt-get update && apt-get install yarn
      # debugging
      - run: pwd
      - run: ls
      - run: echo "${CIRCLE_WORKING_DIRECTORY}"
      # /end debugging
      - run: cd ${CIRCLE_WORKING_DIRECTORY}/web-fort/tf-app
      - run: yarn
    # - npm install:
    #     pwd: tf-app
    # - npm run build:
    #     pwd: tf-app
    # - npm install:
    #     pwd: tf-sched
    # - npm run build:
    #     pwd: tf-sched