version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: apt-get update    
      - run: apt-get install sshpass
      - run: apt-get install apt-transport-https
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - run: apt-get update && apt-get install yarn
      - run: ls
      - run: cd /root/project/web-fort/tf-app && yarn && yarn build
      - run: cd /root/project/web-fort/tf-sched && yarn && yarn build
      - run: cd /root/project/web-fort && ./deploy.sh \$WPENGINE_USERNAME_${CIRCLE_BRANCH^^} $SSHPASS_STAGING

  # deploy:
  #   docker:
  #     - image: node:8
  #   steps:
  #     - run: /root/project/web-fort/deploy.sh treefortfest-staging-deploy $SSHPASS_STAGING
    # - npm install:
    #     pwd: tf-app
    # - npm run build:
    #     pwd: tf-app
    # - npm install:
    #     pwd: tf-sched
    # - npm run build:
    #     pwd: tf-sched

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master