version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run: apt-get update    
      - run: apt-get install sshpass
      - run: apt-get install apt-transport-https
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - run: apt-get update && apt-get install yarn
      - run: ls
      - run: 
        - command: cd /root/project/web-fort/tf-app
        - command: yarn
        - command: yarn build
      - run: cd /root/project/web-fort/tf-sched
      - run: yarn
      - run: yarn build
    # - npm install:
    #     pwd: tf-app
    # - npm run build:
    #     pwd: tf-app
    # - npm install:
    #     pwd: tf-sched
    # - npm run build:
    #     pwd: tf-sched